# Generated by Django 4.2.10 on 2024-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Short description'),
        ),
    ]
